### ISSUE TITLE
Ampersand character ommited from label text

### ISSUE THREAD

**Issue by ceisserer** [eclipse-rap/org.eclipse.rap#111]
When setting the text of a label to a string which contains an ampersand, the '&' is simply ommited from the label's actual text.

e.g.:
	Label l = new Label(parent, SWT.NONE);
	l.setText("Hannes & Werner");

results in:

![grafik](https://user-images.githubusercontent.com/14094579/220840109-d5626df1-5cec-4bd6-9ada-ba29cfc52ac9.png)

**Comment by ifurnadjiev** [comment]
@ceisserer You should use double && in this case. This is by convention in SWT. A single & is used for mnemonic if I'm not mistaken. Will close it as invalid.
