### ISSUE TITLE
CSRF security

### ISSUE THREAD

**Issue by Devip-singh** [eclipse-rap/org.eclipse.rap#117]
Does RAP implement any prevention mechanism against CSRF ? Please let me know if it is already implemented in RAP 3.10
Thanks for any lead on this.

**Comment by ifurnadjiev** [comment]
Yes... RAP use a connection id generated on the server to identify the client UI session. All RAP 3.x versions have this implemented.

**Comment by Devip-singh** [comment]
Thanks a lot for your proactive response !! Much appreciated
