### ISSUE TITLE
Missing RAP artifacts in maven central

### ISSUE THREAD

**Issue by amergey** [eclipse-rap/org.eclipse.rap#130]
I cannot find RAP 3.25 (2023.06) in maven central, last available version is 3.24
I did not find any anouncement related to RAP not pusblised anymore in maven central, so I guess it is an issue

**Comment by bwolff** [comment]
As I understand it, the Maven release process has to be done manually in a separate step. As a result, the release to Maven central can be delayed.

See also: #95

**Comment by mknauer** [comment]
Indeed, you were right, the bundles were published to Maven just yesterday (caused by an invalidated PGP key...) and would have been available a little later. Anyway, now they are available - see https://search.maven.org/search?q=g:org.eclipse.rap.
