### ISSUE TITLE
[Grid] Index out of bounds exception when using cell selection and setItemCount

### ISSUE THREAD

**Issue by mheiss** [eclipse-rap/org.eclipse.rap#135]
An index out of bounds exception is thrown when setting the item count to a value that is lower than the item index of the currently selected cell.

Sample: The table contains 10 rows. A cell in the second row is selected. When now setItemCount(1) is called an IndexOutOfBoundsException is thrown. 

```
    @Override
    public int createUI() {
        int result = 0;

        Display display = new Display();
        Shell shell = new Shell(display);
        shell.setLayout(new FillLayout());

        Grid grid = new Grid(shell, SWT.VIRTUAL | SWT.BORDER | SWT.V_SCROLL | SWT.H_SCROLL);
        grid.setCellSelectionEnabled(true);
        grid.setHeaderVisible(true);
        grid.addListener(SWT.SetData, (e) -> {
            GridItem item = (GridItem) e.item;
            item.setText(0, String.valueOf(e.index));
            item.setText(1, String.valueOf(e.index));
        });

        GridColumn column = new GridColumn(grid, SWT.NONE);
        column.setText("Column 1");
        column.setWidth(100);

        GridColumn column2 = new GridColumn(grid, SWT.NONE);
        column2.setText("Column 2");
        column2.setWidth(100);

        shell.setSize(500, 500);
        shell.open();

        grid.setItemCount(10);
        grid.setCellSelection(new Point(1, 1));
        grid.setItemCount(1);

        return result;
    }
```

The internal 'selectedCells' member is not updated when the item count is modified. Anyone that now tries to do something with that selected cells will cause exceptions. 

We are using RAP 3.23.0 currently. But i did not see a fix for that issue so it should be present in the latest version.

[stacktrace.txt](https://github.com/eclipse-rap/org.eclipse.rap/files/12320017/stacktrace.txt)

**Comment by ifurnadjiev** [comment]
The cell selection is not compatible with virtual Grid... A lot more work is need here in order to make the cell selection works with virtual grid.

**Comment by mheiss** [comment]
It is also broken with non-virtual grids ;)
The simples possible fix would be to clear the invalid selected cells when setting the new item count.
Not sure if that would be enough?
