### ISSUE TITLE
Replace dependency to org.eclipse.osgi.services 

### ISSUE THREAD

**Issue by HannesWell** [eclipse-rap/org.eclipse.rap#160]
The bundle `o.e.osgi.services` is deprecated for removal as part of https://github.com/eclipse-equinox/equinox/issues/18 and already has been changed to be empty and only re-export the 'official' OSGi artifacts published to Maven-Central.
It should be replaced by imports of the desired `org.osgi.service.*` packages so that the runtime can choose a suitable provider independently of the bundle name.

In the case of RAP it looks like it is only used in the target-platform feature, maybe you can just remove it and all dependencies are pulled in as transitive dependencies.

**Comment by mknauer** [comment]
Yes, that is a good point with the target-platform-feature.
We should take that as an opportunity to think about these features in general. They were meant to provide a tested set of bundles for a RAP environment based on OSGi, i.e. as a starting point for developers doing their own work, but these days there are other ways to achieve that, and using our target platform features can probably replaced by a more modern approach.

**Comment by HannesWell** [comment]
Could you already make progress on this one?
It is not urgent. It should just not be forgotten :)

**Comment by mknauer** [comment]
No, I can assure you that it is not forgotten. :slightly_smiling_face: 
In the 2024.03 timeframe I won't have the time, but we should consider that for our release in June.

**Comment by HannesWell** [comment]
> In the 2024.03 timeframe I won't have the time, but we should consider that for our release in June.

The June release just happened so it could be a good opportunity to consider this again :)
Just stumbled upon this again because since the marketplace client replaced it's usage, RAP and Acelleo are the only two projects in the SimRel still using that bundle.

**Comment by mknauer** [comment]
It is not forgotten. Actually I started to implement that change in the last release, but then decided to postpone it, because it turned out we released a "maintenance" release only without any additional changes. Our release in September will contain a larger rework of many parts, therefore it is a good candidate for that one.

**Comment by HannesWell** [comment]
Awesome. Thank you!
