### ISSUE TITLE
Which RAP version is supporting Java 21?

### ISSUE THREAD

**Issue by xsenko** [eclipse-rap/org.eclipse.rap#163]
If I'm not wrong Eclipse 4.29 is supports Java 21, but I couldn't find which RAP version is supporting Java 21?
Right now we are using RAP 3.23, If I start to use RAP 3.23 with Eclipse 4.29 can I use it with Java 21?

**Comment by ifurnadjiev** [comment]
Yes. You can. Latest RAP development platform requires Java 17 at least.
