### ISSUE TITLE
ServerPushSession is interrupted after a period of inactivity

### ISSUE THREAD

**Issue by MatthiasBoehm87** [eclipse-rap/org.eclipse.rap#167]
Environment: RAP 3.27

We've recently switched from RAP 3.25 to RAP 3.27, and noticed, that the ServerPushSession we use gets interrupted after a certain period of inactivity. If the ServerPushSession is not used (i.e., no `Display.syncExec` or `Display.asyncExec` methods are called), the following is shown in the browser's console after some time:

![image](https://github.com/eclipse-rap/org.eclipse.rap/assets/104501930/5ec16792-4959-44b9-9928-80c63133010e)

After this message in the console the ServerPushSession doesn't work anymore.

It may last 5 minutes, but also more than 12 minutes until this message appears.

We've investigated this further and found out, that the problem occurs also in RAP 3.25, only that it then lasts 30 minutes or so until the error message above appears.

If the ServerPushSession is used regularly (by calling `Display.syncExec` or `Display.asyncExec`), this problem doesn't occur.

Attached is a basic sample application with which this bug can be reproduced: [ServerPushSession.zip](https://github.com/eclipse-rap/org.eclipse.rap/files/14258508/ServerPushSession.zip)

**Comment by ifurnadjiev** [comment]
Is this happen in Chrome only? Or Firefox is affected too?

**Comment by fappel** [comment]
> As a workaround, we execute Display.asyncExec every 10 seconds in a Worker-Thread that is created during UI initialization. The code executed by Display.asyncExec just reads the title of the current shell and sets it to that value again, so that nothing is actually changed by the asyncExec invocation, but the UI is updated, nevertheless.

Just a side note: If you use Display#timerExec in a recursion like shown below you might be able to omit the worker thread. At least it work's for me without worker thread, but my motivation for doing this was different.

private void scheduleNextContentUpdate() {
        Display.getDefault().timerExec(10_000, () -> {
                // do the shell magic to force an update
                scheduleNextContentUpdate();
            }
        });
    }

**Comment by MatthiasBoehm87** [comment]
The problem occurs both in Edge, Chrome, and Firefox, albeit in Firefox the console output is different:

![image](https://github.com/eclipse-rap/org.eclipse.rap/assets/104501930/53884700-720b-4a95-9de9-dd8e8e446cf4)

In the network tab in Firefox one can see the interrupted ServerPushSession (displayed with red font and marked with 🚫 in the first column):

![image](https://github.com/eclipse-rap/org.eclipse.rap/assets/104501930/4cd6cd16-3e17-484c-acae-10ad37cbcbc7)
