### ISSUE TITLE
Deadlock in JobManager on Startup

### ISSUE THREAD

**Issue by ChristianHoesel** [eclipse-rap/org.eclipse.rap#195]
RAP Version: 3.29
Java 21

Since we updated from RAP 3.26 to RAP 3.29 we see sometimes (about 1 out of 5 attempts) a deadlock within the JobManager on startup in the UIThread.

Please see the attached thread dump for details.
[20240626.txt](https://github.com/user-attachments/files/15986919/20240626.txt)

**Comment by ifurnadjiev** [comment]
Is it possible to provide a snippet to reproduce the issue?

**Comment by ChristianHoesel** [comment]
When I was looking deeper into the stacktrace I saw that there might be a connection to the use of activity extension points, but that is only a guess.

I will try to provide a snippet, so far I had no luck.
Please give me some time - I will be on vacation for the coming weeks.

**Comment by ChristianHoesel** [comment]
I was not able to reproduce it and to provide an example.
