### ISSUE TITLE
pack for column

### ISSUE THREAD

**Issue by demetr88** [eclipse-rap/org.eclipse.rap#197]
I'm not sure that's bug but
if i'm using pack for column in TableViewer and set bold font for value to pack doesn't work correctly  because  width is set  for normal text and so set to the end of value "..." as of extra
![screen_ 2024-06-27_01-45-48_PM](https://github.com/eclipse-rap/org.eclipse.rap/assets/63187191/fdfe5a89-d496-4ebd-b587-bab095584b59)

**Comment by ifurnadjiev** [comment]
The `org.eclipse.swt.widgets.TableColumn.pack()` is using the header font, but not the item font. For items the `org.eclipse.swt.widgets.TableItem.getPackWidth(int)` is using the Table font. For performance reasons the individual item font is not evaluated. That's the SWT behavior too.
