### ISSUE TITLE
[Scripting] MouseWheel scroll direction / count in Event Object

### ISSUE THREAD

**Issue by slgodyo** [eclipse-rap/org.eclipse.rap#20]
In order to listen to mousewheel events in RAP, you have to implement a client side listener:

`component.addListener(SWT.MouseWheel, clientListener);`

Inside the javascript file you can process the event in the `handleEvent` function

```
var handleEvent = function( event ){
 // process event
};
```

However, the event does not provide any information on the scroll direction, like the swt mouseEvent.count, which would be very useful in the event processing.

The only information I get are:
```
{
  button: 1
​  stateMask: 0
​​  type: "MouseWheel"
​​  x: 485
​​  y: 184
}
```

Is it possible add a property like the swt count or the javascript deltaY to get information about the scroll direction?

**Comment by ifurnadjiev** [comment]
How the `count` property can be used for direction detection?

**Comment by slgodyo** [comment]
Thanks for the rull request!
This is exactly what I was looking for
