### ISSUE TITLE
Option to restrict text measurement cache to session scope

### ISSUE THREAD

**Issue by ceisserer** [eclipse-rap/org.eclipse.rap#22]
The text size measurement cache used by RAP seems to be the root cause of some strange artifacts we have been observing for a long time with one of our applications: https://www.eclipse.org/forums/index.php/t/1106089/

The current approach works as follows:
- at startup, send a probe containing some constant string to the browser and measure it
- get the result and look into the probe cache, to find if another browser has returned the same result for the current font+style+size
- if so, assume the current client will render **all** strings identical to the previously seen, which implies:
  1. text mesurement requests from the current client can be fullfilled from cached data generated by the previous client
  2. text mesurements performed by the current client can be used by other clients which return the same result for the initial measurement probe

However this approach seems to be fragile:
- the initial probe contains only some (ascii) characters
- special glyph positioning rules (e.g. less spacing under some special conditions) are not detected and lead to ugly work arrounds like the fix for bug 374914
- local conditions of the client which can change **AFTER** the initial probe has been computed can not be detected and poison the cache

consider the following circumstances:
- visually impaired user loads a RAP application, and initial probe returns a match
- the default font used is not suitable for the user, so he uses a browser plugin to change/overrides the font + size to something more readable
- the user now navigates through the application, the rendering he observes is broken by the cached values from other browsers and worse he poisens the cache with the wrong measurements performed by his client.

So as long as the cache does not overflow, **the only way to fix broken rendering for all other clients is to restart the application.**

I admit the above scenario is rather constructed, but in production we have been observing corrupted text measurement caches frequently and can not pinpoint the source. Maybe browsers return different measurements once the zoom level is changed while the application is used. Maybe special characters not contained in the probe cause mismatches. Maybe some users use plugins to overwrite the font chosen during use. We simply don't know and I can't think of ways to find the cause.

My point is the current approach - while worthwhile - seems to be rather fragile. There are so many things that can go wrong and once one thing happens at one client, it has negative effects on all other clients with the same initial probe result (which can be basically everybody in a standardized office environment).

Therefore I would propose an option, which allows to restrict caching of text measurements to session scope. So each client has its own measurement cache, and if something goes wrong only this client's rendering is broken until the next reload - not everbody else' too until the system is restarted.

If this would be of interrest / has a chance to get upstream, I would provide a patch.

**Comment by ifurnadjiev** [comment]
With your suggestion every session will be overloaded with a lot of text-size-determination requests, which will trigger the UI re-layout (flickering). As a result the server performance will degrade with too many sessions in parallel.

**Comment by ceisserer** [comment]
I agree this won't come for free - that is why this cache was implemented in the first place. However I proposed to make it optional via a switch and leave caching enabled by default, so in case users experience problems, they at least have the ability to turn it off instead of restarting the application regulary.

The reason my proposal is so drastic is that current implementation simply isn't robust  - measure text once and if it matches take for granted the client will render all other texts the same way too requires some luck ;)

The only solution I can think if to make it really solid and keep caching in place  is to re-validate each cached measurement again on the client and re-measure / re-layout in case a mismatch is detected. However I guess this would mean quite a lot of infrastructure work within rwt...

**Comment by ifurnadjiev** [comment]
Clemens, as it seems that you already have a "solution" in hands, it will not hurt to provide a patch (pull request) and discuss the details on top of it.

**Comment by ifurnadjiev** [comment]
Something came to my mind. In RAP theming the default font is defined as "family" of fonts like:
`font: 14px Verdana, "Lucida Sans", Arial, Helvetica, sans-serif;`
Is it possible that the text size measurement is different for Verdana vs Arial vs Helvetica in different systems (browsers)? The overall RAP font probe size will be the same (cached), but if one browser is using Verdana and other Arial and the sizes differ than the described issue is possible.

**Comment by ceisserer** [comment]
@ifurnadjiev I've opened a pull request to illustrate how storing the text meausrements in the session could work. I had deployed this approach in a production environment ~2017.
