### ISSUE TITLE
Rap 4.0.0 Maven deploy is missing on Maven central 

### ISSUE THREAD

**Issue by theanuradha** [eclipse-rap/org.eclipse.rap#230]
Rap 4.0.0 bites not yet available on maven central

**Comment by mknauer** [comment]
In comparison to older releases, there are a few new artifacts with RAP 4.0, which is the reason for the delay.
As of today, there is a staging repository available, and I'd be interested in getting some feedback before releasing it. The staging repository with the RAP 4.0 bundles can be found at

> https://oss.sonatype.org/content/repositories/orgeclipserap-1097/

**Comment by theanuradha** [comment]
Perfect I’ll test it out

Best regards,

Anuradha G

**Comment by mknauer** [comment]
Published today.
