### ISSUE TITLE
Example WARs are not deployable

### ISSUE THREAD

**Issue by friedrichpit** [eclipse-rap/org.eclipse.rap#243]
Hello, I built the examples and tried to deploy them on Wildfly 30.0.1.Final and Tomcat 11.0.0. It works on neither of them. I always get an 404 Error: "BridgeServlet: /rapdemo". Apparently there are classloading issues. When the Activator of the org.eclipse.rap.http.servlet-Bundle is invoked then the static instance of the BridgeServlet is null. There seems to be two BridgeServlet-Classes loaded by different ClassLoaders.

RAP Version: 4.0.0.20240731
JDK Version: 21.0.3+7-LTS-152

@ifurnadjiev

**Comment by ifurnadjiev** [comment]
Thank you for the report. We are looking at the deployed problem.

**Comment by ifurnadjiev** [comment]
@friedrichpit Are you using released RAP 4.0 repo? Or you are building the demo against current RAP 4.1 main branch (or milestone)? For us, the demo war file is working fine in Tomcat 11 and Java 21 when we are using the released RAP 4.0, but failed with RAP 4.1 milestone/nightly.

**Comment by ifurnadjiev** [comment]
How do you built the WAR file?

**Comment by friedrichpit** [comment]
@ifurnadjiev 
I built the examples as described on https://github.com/eclipse-rap/org.eclipse.rap/blob/main/releng/org.eclipse.rap.examples.build/README.md.

I checked out the 4.0.0-R tag.

**Comment by friedrichpit** [comment]
@ifurnadjiev 
Sorry, apparently I didn't set the rap-repo.url-Property the use the stable version. The example seem to work fine now. I run a few tests and then I'll close the issue.
Thank you.

**Comment by ifurnadjiev** [comment]
We are trying to figure out the issue with RAP 4.1 milestone now.

**Comment by friedrichpit** [comment]
Closing
