### ISSUE TITLE
New entry for "Built on RAP" page - NetXMS

### ISSUE THREAD

**Issue by 2128506** [eclipse-rap/org.eclipse.rap#25]
Web UI for NetXMS (open source monitoring platform) is built on RAP.
References:
Source code - https://github.com/netxms/netxms
Product home page - https://netxms.org

**Comment by mknauer** [comment]
Thanks, looks very nice.

Would you be able to provide one or two descriptive sentences, maybe a reference, and a screenshot that highlights the usage of RAP? The style and content should be similar to the other examples on the https://www.eclipse.org/rap/users/ page.

**Comment by 2128506** [comment]
Product description:
```
NetXMS is a powerful open source monitoring solution for telecommunication networks and IT infrastructure. It provides lot of usual instruments for network administrators: automated topology discovery, topology-based event correlation, flexible data collection, scripts for automation, and many more. NetXMS can be scaled from monitoring few devices to monitoring tens of thousands, with millions of metrics.
User interface for NetXMS initially was developed for RCP and later successfully ported to RAP.
References:
    NetXMS web site (https://netxms.org)
    Source code (https://github.com/netxms/netxms)
```
Sample screenshot attached.
![netxms-rap-screenshot](https://user-images.githubusercontent.com/3931184/172888861-0f96e9f5-6a5d-4ac5-a7c3-aab4aeba3858.png)

**Comment by mknauer** [comment]
The entry is now listed on our [Built on RAP](https://www.eclipse.org/rap/users/) page:

![image](https://user-images.githubusercontent.com/526000/173750263-8d6d3beb-6617-4a90-9a8d-d21ea64ecdae.png)

Thank you for using RAP!
