### ISSUE TITLE
org.eclipse.rap.http.jetty not available on maven central

### ISSUE THREAD

**Issue by amergey** [eclipse-rap/org.eclipse.rap#256]
It seems `org.eclipse.rap.http.jetty` is not available on maven central which forces to use p2 to get it

**Comment by mknauer** [comment]
We intentionally skipped uploading the `org.eclipse.rap.http.jetty` bundle to Maven Central, as it wasn’t part of our Maven Central release for version 4.0 either. At that time, I assumed its primary and perhaps only use case was within the PDE environment alongside RAP Tools, making its distribution via p2 sufficient.

However, I now understand that you’re building your application with Maven and intend to use this bundle to manage the HTTP service and provide it via Jetty. To address this, I’ve created a `pom.xml` file to upload the bundle to Maven Central, ensuring the dependencies are resolved similarly to p2. A temporary version is now available at:

  https://oss.sonatype.org/content/repositories/orgeclipserap-1099

@amergey, could you please test it in your setup and let me know if it works as expected? Your feedback will help confirm that this approach meets your requirements. Thank you!

**Comment by mknauer** [comment]
I've clicked the `release` button now.

**Comment by amergey** [comment]
sorry for late answer, but I confirm you it works
