### ISSUE TITLE
[JS] On the DateTime widget the UI for the SWT.DROP_DOWN handling doens't work properly with dates < 01/02/1970

### ISSUE THREAD

**Issue by jfuerter** [eclipse-rap/org.eclipse.rap#29]
What's working fine:
- The widget has no issue in displaying existing dates prior to 01/02/1970 
![grafik](https://user-images.githubusercontent.com/108717055/177265409-69eb0405-d4cc-4e78-9ffd-1d99721be17e.png)
- Such dates can easily be inserted with the keyboard or by scrolling with the mouse wheel
- When clicking on the 'Arrow' Button ![grafik](https://user-images.githubusercontent.com/108717055/177265513-881089b1-a40d-4a82-ba3a-cba83291820e.png) the calendar component is opened and the existing date is also visible and selected just fine 
![grafik](https://user-images.githubusercontent.com/108717055/177265600-838acd1b-df19-4139-82e1-c1254e5bd983.png)

What's not working:
- Now, when I select any date prior to 01/02/1970. No matter if I click on a day or I use the change buttons (by year or by month) at the top, the new date is not accepted and the previous date is kept.

As far as I can see this is solely an JS issue. The following method in the **DateTimeDate.js** is blocking any date with milliseconds prior to 01/01/1970 (in my case 01/02/1970, probably due to a timezone?)

    _onCalendarDateChange : function() {
      if( !this._internalDateChanged ) {
        var milliseconds = this._calendar.getDate().getTime();
        var min = this._minimum ? this._minimum.getTime() : Number.MIN_VALUE;
        var max = this._maximum ? this._maximum.getTime() : Number.MAX_VALUE;
        if( milliseconds >= min && milliseconds <= max ) {
          this._setDate( this._calendar.getDate() );
          this._sendChanges();
        }
      }
    },

I don't see the reason for these checks, can't they just be removed? Like:

    _onCalendarDateChange : function() {
      if( !this._internalDateChanged ) {
        this._setDate( this._calendar.getDate() );
        this._sendChanges();
      }
    },

I tried it locally and it worked quite fine for me.

If there is anything I can provide to help you with this, please let me know.

Edit: For completeness: The problems occurs because "this._calendar.getDate().getTime();" returns negative numbers for dates prior to 01/01/1970 00:00:00 according to the unix standard for dates.

**Comment by ifurnadjiev** [comment]
The actual problem is in this line: `var min = this._minimum ? this._minimum.getTime() : Number.MIN_VALUE;`
In JS the `Number.MIN_VALUE` "is NOT the most negative number", but the "the smallest positive numeric value closed to zero".
Changing `Number.MIN_VALUE` to `- Number.MAX_VALUE` will solve the problem.

For years below 01/01/1970 00:00:00 the time in milliseconds is negative.

**Comment by jfuerter** [comment]
@ifurnadjiev  Thanks a lot for the fast fix, and I prefer your solution (less changes and having less possible impact on the overall code).
