### ISSUE TITLE
Feature request: "Eye" icon in password text fields

### ISSUE THREAD

**Issue by MatthiasBoehm87** [eclipse-rap/org.eclipse.rap#4]
In many web applications it is possible to unveil the password entered into a password text field by an "eye" icon on the right side:
![image](https://user-images.githubusercontent.com/104501930/165508884-9ae802de-850e-45ce-819f-fd4a933939be.png)
![image](https://user-images.githubusercontent.com/104501930/165509199-3d52d43b-a9d0-4871-b8ea-6799eda160ce.png)
RAP is still missing this functionality. It would be nice, if in the future, RAP would support such an "eye" icon as well.

**Comment by ifurnadjiev** [comment]
There is no such build-in functionality in RAP, but it's not so hard to achieve it with client scripting. Create filed and icon in RWT. Attach client listener to the icon and change the field type from "password" to "text" and back. More information about scripting here [1].

[1] https://www.eclipse.org/rap/developers-guide/devguide.php?topic=scripting.html&version=3.20

**Comment by ifurnadjiev** [comment]
The Nebula project has such a widget: https://wiki.eclipse.org/Nebula_PasswordRevealer

**Comment by ifurnadjiev** [comment]
The main idea here is to use `Text#setEchoChar(...)` to switch between password and text mode.

**Comment by MatthiasBoehm87** [comment]
OK, thank you for the information. I'll give it a try when I have the time for it.

**Comment by ifurnadjiev** [comment]
There is a working implementation (Nebula widget) and also a simple "hand made" solution for this request. I'll close this issue as WONTFIX.

**Comment by MatthiasBoehm87** [comment]
The Nebula widget doesn't work, because it's for SWT, not for RWT. But I managed to implement the eye icon with RAP, RWT and some CSS.
