### ISSUE TITLE
MImperativeExpression not working in RAP E4

### ISSUE THREAD

**Issue by 15knots** [eclipse-rap/org.eclipse.rap#42]
Looks like
`org.eclipse.e4.ui.workbench.renderers.swt.MenuManagerRenderer.updateVisibility(MenuManager, 
MMenuElement, ExpressionContext)` has not been upgraded when imperative expressions were introduced.

**Comment by ifurnadjiev** [comment]
Could you please provide a patch against our e4 demo to demonstrate the problem? A pull request with a fix will also be welcomed if you know exactly where is the problem.

**Comment by 15knots** [comment]
See [MenuManagerRenderer.updateVisibility()](https://github.com/eclipse-rap/org.eclipse.rap/blob/main/bundles/org.eclipse.e4.ui.workbench.renderers.swt/src/org/eclipse/e4/ui/workbench/renderers/swt/MenuManagerRenderer.java#L1114). It does care for `instanceof MCoreExpression` but not for `MImperativeExpression`.

The non-RAP version (which I cannot find ATM) also cares for imperative expression.

**Comment by ifurnadjiev** [comment]
@15knots please test the pull request and let me know if it fixes the issue.

**Comment by 15knots** [comment]
I tried to test it but
`mvn clean package` gave me
[ERROR] Internal error: org.eclipse.tycho.core.ee.UnknownEnvironmentException: Unknown OSGi execution environment: 'JavaSE-17'

No idea how to proceed.

**Comment by ifurnadjiev** [comment]
You need Java 17 to run it.

**Comment by ifurnadjiev** [comment]
You can also use the compiled version of the RAP e4 framework from pull request at:
https://ci.eclipse.org/rap/job/rap-head-runtime-github/31/

**Comment by 15knots** [comment]
I tested it with the compiled framework and con confirm that MImperativeExpression now works, at least for menue entries (I did not test toolbar entries)
