### ISSUE TITLE
Feature: add Eclipse QuickAccess support

### ISSUE THREAD

**Issue by phermsdorf** [eclipse-rap/org.eclipse.rap#5]
Hi,

as a follow up on this forum post: https://www.eclipse.org/forums/index.php?t=rview&goto=1851499#msg_1851499 

I've made an initial attempt to add the Eclipse QuickAccess to Eclipse RAP.
You can view my WIP here: https://github.com/godyo-business-solutions/org.eclipse.rap/tree/features/add_quickaccess_support

What's working (under the hood):
* extension Point mechanism
* most of the default QuickAccess providers

What's not working:
* ViewElement and ViewElementProvider classes  (heavily depending on e4 workbench stuff)
* the UI and the search
  * see QuickAccessContents: on SWT table a listener is registered for SWT.MeasureItem, SWT.PaintItem and SWT.EraseItem which are obviously not available in RAP
  * QuickAccessEntry uses TextLayout which is also not supported in RAP

I'll try to get something running by using the default SWT Table and TableItems, but of course this will look and behave differently, but maybe better than nothing.

Any hint or comments are welcome.

Bye Peter

**Comment by phermsdorf** [comment]
My colleagues and me continued to work on this.
The updated code can be found in the above forked repository.

Currently it looks like this and works:

![image](https://user-images.githubusercontent.com/11061378/173769733-b4120a46-5505-46e5-90e2-259823332d55.png)

We have integrated the QuickAccess into the demo application. You can open the QuickView windows with Ctrl+3.

@ifurnadjiev @mknauer What do you think about the current state? Is there anything that needs to be done before opening a pull request?

Thanks,
Bye Peter

**Comment by ifurnadjiev** [comment]
Hi Peter (@phermsdorf),
creating a pull request will help to keep all the needed changes in a single place and start the discussion/improvements on top of it. So, please create a pull request against current "main" branch.
Thanks
