### ISSUE TITLE
Unsigned Content in 3.22/RC1 repository

### ISSUE THREAD

**Issue by merks** [eclipse-rap/org.eclipse.rap#50]
The RAP RC1 contribution has unsigned content:

https://download.eclipse.org/rt/rap/3.22/RC1-20220831-0943/

All these unsigned artifacts should have PGP signatures, but those are not present as reported here:

https://download.eclipse.org/oomph/archive/reports-extra/rap-3.22-rc1/download.eclipse.org/rt/rap/3.22/RC1-20220831-0943/index.html

I also manually checked this:

https://download.eclipse.org/rt/rap/3.22/RC1-20220831-0943/artifacts.xml.xz

The `org.apache.commons.commons-io` bundle, which I noticed was unsigned from manually testing installs of 2022-09 RC1 RAP, looks like this:
```
    <artifact classifier='osgi.bundle' id='org.apache.commons.commons-io' version='2.11.0'>
      <properties size='5'>
        <property name='download.size' value='327135'/>
        <property name='artifact.size' value='327135'/>
        <property name='download.md5' value='3b4b7ccfaeceeac240b804839ee1a1ca'/>
        <property name='download.checksum.md5' value='3b4b7ccfaeceeac240b804839ee1a1ca'/>
        <property name='download.checksum.sha-256' value='961b2f6d87dbacc5d54abf45ab7a6e2495f89b75598962d8c723cea9bc210908'/>
      </properties>
    </artifact>
```

But it looks like this in the platform's 4.25 I-Builds:
```
    <artifact classifier="osgi.bundle" id="org.apache.commons.commons-io" version="2.11.0">
      <properties size="12">
        <property name="maven-groupId" value="commons-io"/>
        <property name="maven-artifactId" value="commons-io"/>
        <property name="maven-version" value="2.11.0"/>
        <property name="maven-repository" value="eclipse.maven.central.mirror"/>
        <property name="maven-type" value="jar"/>
        <property name="download.size" value="327135"/>
        <property name="artifact.size" value="327135"/>
        <property name="download.md5" value="3b4b7ccfaeceeac240b804839ee1a1ca"/>
        <property name="download.checksum.md5" value="3b4b7ccfaeceeac240b804839ee1a1ca"/>
        <property name="download.checksum.sha-256" value="961b2f6d87dbacc5d54abf45ab7a6e2495f89b75598962d8c723cea9bc210908"/>
        <property name="pgp.signatures" value="-----BEGIN PGP SIGNATURE-----&#10;&#10;iQIzBAABCAAdFiEEnjBEBxt1jry35FZzcA5PObwFNksFAmMSLn0ACgkQcA5PObwF&#10;NksmBw/9GJFNIuqhHOQXz+I5ekcosGTOfw1Bcn2g3B7en5KjVToJYdkywNab1Dbh&#10;DZEzGK5daGZzD5075wa3jx3AmIBN5CJnj8rB1wLgWM4ZMi9VpyDv2mQqORB+RmOr&#10;gZDI/2ovqc9eosZ83/5TaihLL4Hzu95zwwObfPu0OtXexviIGCdkiBKtH+WiQbDV&#10;BVbOj7C6c8GmFTtlgF2zU8UvtVBql2BPzBRhnKSN0DuqjpFXcmM8HZJtpQ1C1i1Z&#10;m4/JlWy9YUvq9ljkK4As57zDePvfeqxng04EL7eGk6KEu2xsDZHgxPYD0bmMbaKn&#10;16CbCFOpVjhhVdhF2wUtGEHmryhZv2hCVg9VEvzxPmjadrVJqdi6CwRDI2xgLxd5&#10;XPUwNlTeI0flPcTUsUOCovx7w/enEC8orYcgEBvZkOxulmm084AhkA2pMSGX6XqS&#10;e5kxCiyiDt1SxaYQ8Qdr7BqFFlICOLu20ncyeROMt3FlsrbhgwS/Du8G1L+Sn5c1&#10;TM4s6EHPotKJmGHgC9vgUwVQ/DPLb0pKcvYVwyfgpOKl5lJvYhWS/sVzcqKvcINU&#10;3GqQLR4PYPcZKXrcKOYgVXobvLEqOeW8IJFAs9B3n9eXVt/Soo1TUZYaQs5Xutb0&#10;3IJxlvyvL4f/KjZa2jGCybhIDj4rODJzNK5h98deJUguXp2Ev3c=&#10;=JH5R&#10;-----END PGP SIGNATURE-----&#10;"/>
        <property name="pgp.publicKeys" value="-----BEGIN PGP PUBLIC KEY BLOCK-----&#10;&#10;mQINBFhaXO0BEAC8WCdwrJNF/W+C8m9FYwAhEvKBvQ7xmoGYZqgcYe2ntT8udvgZ&#10;k+dRwZJnu1VI3a8feOLrAmeNI2MxPP0+l2kGeC55c10duXPzLvW9oHONm39FZpCM&#10;X1m66TYkUBeu/DIttNf5l0nv54dmm4VAWjutnVmlKGf5MVmmAH4mrkmgs7UTyQRK&#10;JKJ8B7tAt6CI1tXq2ULjzUpz9iyD1IkWal4K2gYfooSuGLayNY+SCdcT9uZkpS4B&#10;rnHy2QeJqPSnJv+5G1SkX1fzavWelrf72vx+su8L8QzUa6JtGJatFbAHzEdXGJ98&#10;JnK7TAQvR3hCyzj+TnVCY1hiRO6B+4zI3j/vSJVdc5wmLejvfZRqhiaQ8Vr4xDbu&#10;w7/i+raAKwr//zVGAqp/zN6zQmyoLks+cfuI4yqHuXKGaNs5RapKCxfukC/TRB2e&#10;fLhqCpXAbRQ8a+R+0CCBP2WYDYNQoh4FnwuqtZefnm8NVKW+2we5y3llIrXV5PQb&#10;FFN5WOLuNvO/JOtRQSjNd4WYttwNCDP7ATpRK6ixz7qveztGNhuiCRx01HbZ2uUE&#10;DKV0DW8mWRjALl9/akMRcdIeTayKHDVjeNq5amnWT0vZ2F422BJW6sQryTs/NIBK&#10;XGoVVZeXms3fzL9IpztcVFZTuwmk5kk1FXXaBDMwVHlR5hC5gIuLIfLVEwARAQAB&#10;tDpFY2xpcHNlIFBsYXRmb3JtIFByb2plY3QgPHBsYXRmb3JtLXJlbGVuZy1kZXZA&#10;ZWNsaXBzZS5vcmc+iQI9BBMBCAAnAhsvBQsJCAcDBRUKCQgLBRYCAwEAAh4BAheA&#10;BQJhuzR+BQkSxtkRAAoJELbTq5vMZBKCntUP/i+waQ1AAKEMBuwuP9KbAKNLyTFa&#10;Dl5cbwIcehAne5u7x3CfqYxc2NBCjM20akmYVnTYtvAriLKq9HcycYl98mxfWNOb&#10;/UtO2d04cBWqRn5U9TW0QbXrA3/kScmKzf8qWr2m6DLgl3ZVewapoP9iNYOVeWRB&#10;iI7ap+yLJwlRp0YxPjpgkSeV5+ghFpUG3ppqAIlB5QaNadbG9xIoqcs0x4gdyrUS&#10;uPFX42p6y+JIM31eDW4hKcyo29C8xg4oMQsmL6fZAASP+IXboqjaK/QijA2etVsq&#10;vyv8A+FAzZlV9zEx9EY6aJvIjABDV0IUrbfbmyUckM/sbsy7Wa13koiMIAUu8ylv&#10;HOXkblBqUPDeoZS1KXOpiRHoJ0+WalLWayiWSOiDdMeq2Le0EZvLhvK/No4TZWSl&#10;WEa3IZA/nKHeDI5Sv4NG4kcFyrrgJSphezgF3dU+EePeAtOYv3OWpLbgKbs2BTY3&#10;B7Y36aX6svrJD667bPkjj7EQumJSr6vtEB7YJF5WtXR3voviDACpm0+jJN7KQsmM&#10;X26z6J8VNOqzQvTekRZKr1lSSgECPdHZQaBfTM5ODiOGkVInR0LN9Tx1zriuQdoh&#10;vMlXF/EmuxzKi7TP9MfW6xB6/7gAIJDdEhJni5+Q14U5j6oOaXUzpcFEjg7xyBe7&#10;0/Inw3JlHfp/q2McuQINBFhaXPsBEAC3bR7f5euHbpIDDTuFYHPI0+S5X0DhuqcG&#10;BUL2HSFhWMwIlfsAaO+pt7GyfXLUkTmzugwmwO+sOW2QmwEZQcK2z3BrcjytZoph&#10;Z9AUajbAjnadSH6UXCMmfExVVnaYSfl/+Uub42szQE/r3gCRIz6M6clVVAjpFv4G&#10;/mumfQUV/XzLoUEYXTgwTokFJ97R+hDbHvBEBrUT8M6zHP5DhN3EBug3qb6wZVOa&#10;/+HEX3M+7k4jVT/ppNumw0acg0DDoSNQ13VsRV6sV0XE4zr3Zfs84f8xCgXpEMs4&#10;U6DZGqs3iJVVtbRf0oL0fgcxNgRrmbCrBfbXYfrS4u+fJ0vB+Wrflv9eNA3i6TtV&#10;L6uYpZy9uO2B1olKVzfEhsgB3QrULB4jVHZjIXGe4ILn45ndMtAeY4M91wyobgG9&#10;9Xl+1vPHrxV0+2zRP66J3puyxiKE2B7gd7hib54CB3lYyrG1S+K1kZGCI1IFKCnq&#10;mTJXY0tKoLAASS3vtDcknXenzR5RVSpWTDuxtusekfL0Bw8pCBoz9L4Hex8Q1j//&#10;D5CZlqcg1NKFfmBZ7ta9PTuJcpOsz/LaPG/0VHYt/QAv5o4eeZESl7iZyM4/0NFh&#10;2s/rq0R8Z9yVSSkIvvO8d8XGZ65NTm3T4NFuEihn+AEm+zg4KiGdYBEZvs8QQoW9&#10;e1+MMN8xnwARAQABiQREBBgBCAAPAhsCBQJhuzR9BQkSxtkCAinBXSAEGQEIAAYF&#10;AlhaXPsACgkQcA5PObwFNkunSw//SRR1tGS1pDj2jonLpR0wPilCphS6ANv895yv&#10;lg6rHG4nKi4hQ0JzZxhGCwkgxEkRaKiyLfEiTihETkF161AqLPhyvE8LuQ1AG+A+&#10;tUnR8/T3gKE8t/m2/UtScZwN1QEQVc/uG7MTrbZ2ngXfH65k3fzhjy95AnJHAswu&#10;2vic1hzDi77HlQpN0O3adJuU/jfdu1RxNE0MRt8MFEjsTFwSBVm6lDxgcZV+qjRL&#10;GQznTyLF5/AyCI7Z4z9xHZPKFq1eHzqevifNiqfb8KX22sHKOSdnVBzBq/UxbT5j&#10;IbNSRhD91FjtZD7Z6wi3POsB/9RWZBldCov4ZEajmxFzxpx4RAqYOSIkEor9ZtRG&#10;bZuWvTie4vFIur7Tf543mE6nxKcggExNp4MTyOd1scMc9oyczH561OTdHOCYEyoC&#10;wpG9N2Hb1/MDnWSiHKG451CvdrE5FHcPZKjp/nHUcRw/WQC3bgj6ScAay64EKC5S&#10;9tW+Wp85Oyyvj+M7lBzOxp19nESpfC++fzBAQPMxtD8EvrZTxqFSJxMOH9bhzB8+&#10;MFt08tmYb5SwoYi4C8JJ+wZgNetJKK+j07fvyMUChH/SbkCVszMiiSEjHA2Kk0LM&#10;VYKS/OLJU7i7tZXVaJ078QEeTDy5hSzsutd+orlFkR9+mgr1HUh0UgYlofTfEi7b&#10;LDeSr0cJELbTq5vMZBKCicIP/irazYBVKw0SluhHtjzRcs5WIdH5bVPsEE87+iUc&#10;4daONWdVIhLdokxtOWlrEmZFLKqq9Z8fzvlf5LAQMOBkMAkl0z2ej4KG7zrjWyqD&#10;gysEI2WBlqTAFSeL+89Kc9BzJE9heYW8EfpXbNfOnKnAYWsbhcomSxVQ/jBIuyLB&#10;g/0gYKpBNx8HC6v9xNH0Ja+wM/7w3JC1aIwMYJn1yF2ykUYS+BoTCU7TA8r43pHg&#10;4I4Fz+Y2P5RLk+RJI4kJezDNiJOpIcr/nKTPxMGUzMtWlGyAJ7LkyOZCtQXhtXwa&#10;T8grjtHzlwlGrpgDRtf7wWjzEWeaQSegTFM9Mid+09kCp0PkJvveg8wJCuoVboNO&#10;to0O5rQsUczjXxiWkXYlHGeQL4rWc1zP7F1n4DEwDbVZC7jOn/80l3x4LcKuhc86&#10;gP4L5HKbdjn5GcQ03RVLl1WVTQCdpr0+am28hl9XpyHdlWwSEmqqoUnjGv5B8RCl&#10;ocBRS4ECPPZCVSBlyK8eDgRww9Fu1EFq4xkq5fGj4YUOAIm756iW41NQ3VnPYbom&#10;/J27iFFN8+h92CSbKAqhmRwQh+GGo0eGCXmPHyQ/KCHTvnTZCFBUvabm3rVNFaDO&#10;+RvmwPwNCRz0DYzGpaeMOGo4nMMGbzdhgfJ/X5Ed1/Mqz8egHhGIO94ebKEN5ZtJ&#10;jAOK&#10;=EmXb&#10;-----END PGP PUBLIC KEY BLOCK-----&#10;"/>
      </properties>
    </artifact
```

From the sha-256, I can see it's the same artifact.

What version of Tycho is being used for the builds? You must use a newer version such as 2.7.3 or 2.7.5.  If you are pulling directly from Maven yourself, you must PGP sign it...

**Comment by merks** [comment]
Note that the tools repository is similarly not in good shape:

https://download.eclipse.org/oomph/archive/reports-extra/rap-tools-3.22-rc1/download.eclipse.org/rt/rap/tools/3.22/RC1-20220831-0943/index.html

I'll investigate and update this comment...

**Comment by mknauer** [comment]
Hmm, could be the Tycho version.
All bundles in question are just redistributed by us and taken from
Platform and from a WebTools (i.e. the Jetty bundles) p2 repository.
With only one day left for building RC2 (and no time to work on it...) it
will be challenging to fix that in time.

Thanks
Markus

**Comment by merks** [comment]
@mknauer I think just rebuilding will do the trick.

One other bad thing I noticed, because I wondered why the Jetty bundles aren't causing the same type of problem.  There I notice that someone has jar-signed the contents here:

https://download.eclipse.org/webtools/jetty/10.0.11/repository/plugins/

So now there are two versions of the "same" artifact floating around in the mix.  The ones the platform provides are only PGP signed but the ones WTP produces are jar signed; I'm quite sure the jar signed one will not validate against the PGP signature of the one that is not jar signed, so there is a problem just waiting to happen.

If you produce a new build using Tycho 2.7.5 as in the PR, let me know and I'll rerun the test (or just look in the artifact.xml and check that the `pgp.publicKeys` property is present for org.apache.commons.commons-fileupload and org.apache.commons.commons-io.

I think this problem first cropped up from this commit:

https://github.com/eclipse-rap/org.eclipse.rap/commit/488739ddcb2de3a3e2c99c26823155ff42c0c8fd

**Comment by mknauer** [comment]
I was working through my inbox from the latest to the older messages, therefore saw your investigation and PR just now.

In the meantime I did exactly what you proposed, i.e. just updating Tycho locally and running a local test build. Because that was successful, I am going to move forward with this and will provide a preliminary "RC2" (or RC1a) this morning which we can use to check whether I am going into the right direction.

Regarding the Jetty bundles from the WTP p2 repository... I don't have a good idea yet how to solve that.

I'll keep you updated about my progress on this issue.

**Comment by mknauer** [comment]
- Tycho is now upgraded to 2.7.5 in both, Runtime and Tools
  - RAP Runtime with PR #51 and commit a6fc2d0468f481ba5d80fed7bade6575b3c953b3
  - RAP Tools with commit eclipse-rap/org.eclipse.rap.tools@c8f79883d484d80b3a00a169d40a0847d79f59af
 - Build is now "prepared" for RC2
 - With [Gerrit Change 195593: Publish RAP 3.22 RC2 for 2022-09 RC2](https://git.eclipse.org/r/c/simrel/org.eclipse.simrel.build/+/195593) I contributed a first test-RC2 to the Simultaneous Release; the verification job succeeded and I merged the current status

@merks Can you please run your tests again? That would allow us to verify if and what problems are solved now.

**Comment by merks** [comment]
The RC2 versions both look good now

- https://download.eclipse.org/oomph/archive/reports-extra/rap-runtime-3.22-rc2/download.eclipse.org/rt/rap/3.22/RC2-20220906-0913/
- https://download.eclipse.org/oomph/archive/reports-extra/rap-tools-3.22-rc2/download.eclipse.org/rt/rap/tools/3.22/RC2-20220906-0913/

Thanks again for the ultra speedy fix!

**Comment by mknauer** [comment]
Always a pleasure!

Does your test cover the Jetty bundle issue that you mentioned in your comment above, too? Because if this would be magically resolved, it would be perfect.

**Comment by merks** [comment]
In the runtime repo there are these Jetty bundles:

![image](https://user-images.githubusercontent.com/208716/188614602-b2decf38-4397-481b-a2be-41fe0464590b.png)

These are PGP-signed:

![image](https://user-images.githubusercontent.com/208716/188614835-db9f4b73-bfc2-4540-9b8c-1bbcd9732e51.png)

While these are jar-signed:

![image](https://user-images.githubusercontent.com/208716/188615309-fe2abfcc-7694-4e50-98ee-de17e661b783.png)

Nothing will magically fix this.  But in both cases other projects are producing the IUs that you are consuming, so you cannot fix this problem, except maybe to replicate the work of the other projects.

In any case, the 2022-06 release shipped this same/similar way with PGP-signed content for the Jetty stuff contributed by the platform and jar-signed content for the additional bundles contributed by WTP.

https://download.eclipse.org/oomph/archive/reports-extra/releases-2022-06-202206151000/download.eclipse.org/releases/2022-06/202206151000/

**Comment by mknauer** [comment]
Thank you for this analysis, that helped me a lot!
I am going to close this issue then, and will contact WTP in parallel. Maybe they can change their p2 repository with the Jetty bundles.
