### ISSUE TITLE
Wrong UI calculation for horizontal scrollbars since Chrome 105

### ISSUE THREAD

**Issue by jfuerter** [eclipse-rap/org.eclipse.rap#53]
Since Chrome 105 (same with Edge 105), as soon as a horizontal scrollbar appears, the UI assigns clicks to the scrollbar not only for the place where the scrollbar actually is present, but also for an area of about the same size below. I've included an example below. We can always reproduce it with the ScrolledForm of a FormPage.

In this screenshot, all the yellow area is actually handling the scrollbar. I only have a small area at the bottom of the pages where I can switch to one of the other pages.
![Scrollbar bug](https://user-images.githubusercontent.com/108717055/188819257-1da96962-3df4-4bc1-ae98-a06667cae6f7.PNG)

Info: 
- Tested with Eclipse RAP 3.21 (and 3.19)
- The problem didn't occur before Chrome 105 (we tested it against 104).
- We use the 'business' theme (maybe the problem doesn't occur with the default theme?)

Here an example how we can reproduce the problem with as little code as possible:

**Editor Input**
```
package test;

import org.eclipse.jface.resource.ImageDescriptor;
import org.eclipse.ui.IEditorInput;
import org.eclipse.ui.IPersistableElement;

public class TestEditorInput implements IEditorInput {

    @Override
    public String getName() {
        return "title"; //$NON-NLS-1$
    }

    @Override
    public boolean equals(Object obj) {
        if (obj instanceof TestEditorInput) {
            return true;
        }
        return false;
    }

    @Override
    public <T> T getAdapter(Class<T> adapter) {
        return null;
    }

    @Override
    public boolean exists() {
        return false;
    }

    @Override
    public ImageDescriptor getImageDescriptor() {
        return null;
    }

    @Override
    public IPersistableElement getPersistable() {
        return null;
    }

    @Override
    public String getToolTipText() {
        return getName();
    }
}
```

**Editor**
```
package test;

import org.eclipse.core.runtime.IProgressMonitor;
import org.eclipse.ui.PartInitException;
import org.eclipse.ui.forms.editor.FormEditor;

public class TestEditor extends FormEditor {

    public static final String ID = TestEditor.class.getName();

    @Override
    protected void addPages() {
        try {
            addPage(new TestPage(this));
            addPage(new TestPage(this));
            addPage(new TestPage(this));
            addPage(new TestPage(this));
            addPage(new TestPage(this));
        } catch (PartInitException e) {
            // ignore for this test
        }
    }

    @Override
    public void doSave(IProgressMonitor monitor) {
        throw new RuntimeException("The method doSave is not yet implemented for class EditorPart"); //$NON-NLS-1$
    }

    @Override
    public void doSaveAs() {
        throw new RuntimeException("The method doSaveAs is not yet implemented for class EditorPart"); //$NON-NLS-1$
    }

    @Override
    public boolean isSaveAsAllowed() {
        return false;
    }
}
```

**Page**
```
package test;

import org.eclipse.swt.SWT;
import org.eclipse.swt.layout.GridData;
import org.eclipse.swt.layout.GridLayout;
import org.eclipse.swt.widgets.Composite;
import org.eclipse.swt.widgets.Label;
import org.eclipse.ui.forms.IManagedForm;
import org.eclipse.ui.forms.editor.FormEditor;
import org.eclipse.ui.forms.editor.FormPage;
import org.eclipse.ui.forms.widgets.ScrolledForm;

public class TestPage extends FormPage {

    private static final String ID = TestPage.class.getName();

    public TestPage(FormEditor editor) {
        super(editor, ID, "Title"); //$NON-NLS-1$
    }

    @Override
    protected void createFormContent(IManagedForm managedForm) {
        ScrolledForm form = managedForm.getForm();

        Composite body = form.getBody();
        body.setLayout(new GridLayout());

        Label label = new Label(body, SWT.NONE);
        label.setLayoutData(new GridData(6000, -1)); // almost guarantees a horizontal scroll bar
        label.setText("label"); //$NON-NLS-1$
    }
}
```

**Comment by ifurnadjiev** [comment]
Just updated to Chrome 105 and I can't reproduce it with our Controls Demo and with Workbench Demo (business theme). I'll give your snippet a try when I have time

**Comment by jfuerter** [comment]
I'm sorry, I should have mentioned that. I already tried to reproduce it in the Controls and Workbench Demo but couldn't find a similar place. And maybe the problem doesn't affect all ScrolledComposites but only ScrolledForms (as used in my example).

**Comment by jfuerter** [comment]
@ifurnadjiev I'm more than willing to debug this problem in order to provide a possible solution for the issue. 
To avoid spending hours after hours in the wrong place, could you please give me a hint where to look?

**Comment by ifurnadjiev** [comment]
Probably you can debug it by inspecting (in Chrome dev tools) first the horizontal scrollbar div height. The client-side handling of the ScrolledComposite is done in Scrollable.js where the two scrollbars are positioned. 
Is it possible to create a self-running project to demonstrate the issue?

**Comment by jfuerter** [comment]
While debugging in Chrome I thought I'd found the problem. (I had a scroll area with a bottom position of -17 and a height of 708 Pixels, as soon as I changed the bottom position to 0 and the height to 691 Pixels it worked as excepted). But I found out that calculation was the same in Chrome 104 and there it worked quite fine.
![Wrong height calculation](https://user-images.githubusercontent.com/108717055/191025596-293edde1-a9ee-4649-9230-3aacc0002eb1.jpg)
![Wrong height calculation 2](https://user-images.githubusercontent.com/108717055/191025706-fafcd7ab-f63b-4eb0-814d-1833574b58d4.jpg)


So I prepared a simple Projekt based on the 'RAP Mail Template' using the classes above. It turned out, the key to the problem is that it only occurs when I'm using the **business.css** from **org.eclipse.rap.design.example_3.22.0.20220617-1351.jar**.

Do you want me to upload the sample projekt somewhere or do you prefer to reproduce it with the **business.css** yourself?

**Comment by ifurnadjiev** [comment]
Is the .css file the only difference in the mail demo? Probably some CSS definitions in the **business.css** are not updated accordingly. 
Please upload the demo project somewhere in order to get it from there.

**Comment by jfuerter** [comment]
Here is a link to the demo projekt (only available for 7 days): https://we.tl/t-IbvuSW8pqU
After starting the webapp you have to klick on the '+' icon to open the editors with the horizontal scrollbars to reproduce the problem:

![grafik](https://user-images.githubusercontent.com/108717055/191050054-385c4c05-4874-4ef2-8ee9-dd6684d52fb4.png)


Otherwise here the description what I did to the mail template projekt:

The mail template doesn't have the required editor (to reproduce the problem). I've integrated all the classes above in the corresponding packages, extended the plugin.xml by the following:
```
   <extension
         point="org.eclipse.ui.editors">
		<editor
			class="test.TestEditor"
			default="false"
			id="test.TestEditor"
			name="Test (NON-NLS)">
		</editor>
   </extension>
   <extension
         point="org.eclipse.rap.ui.themes">
      <theme
            file="theme/business.css"
            id="test.theme"
            name="Theme (NON-NLS)">
      </theme>
   </extension>
   <extension
         point="org.eclipse.rap.ui.branding">
      <branding
            id="test.branding"
            themeId="test.theme"
            title="test">
            <additionalHeaders>
				<meta name="robots" content="noindex, nofollow, noarchive, nocache, nosnippet" />
			</additionalHeaders>
      </branding>
   </extension>
```
Changed the entrypoints definition to use the branding:
```
   <extension
         id="mailapp.entrypoints"
         point="org.eclipse.rap.ui.entrypoint">
      <entrypoint
            applicationId="Issue_53.mailapp"
            brandingId="test.branding"
            id="mailapp.entrypoint"
            path="/mail">
      </entrypoint>
   </extension>
```

And you have to add the business.css as well as the required 'img' and 'theme/resources' folders from the mentioned .jar file.

To open the editors I changed the 'OpenViewAction' to open my TestEditor instead of the default one.

**Comment by ifurnadjiev** [comment]
I can reproduce it with the provided test project. I'll investigate it when the time permits.

**Comment by jfuerter** [comment]
Thanks a lot, I'm looking forward to it.

**Comment by jfuerter** [comment]
Thanks alot for the quick fix! I really appreciate it.

**Comment by theanuradha** [comment]
@ifurnadjiev how can anyone get it on custom components ? as I have html base custom components and all scrollbars is gone now ? can I use some style to get back default like before inside custom component div ?

**Comment by theanuradha** [comment]
@ifurnadjiev what should I use Im trying but it not get me the native scroll inside div

**Comment by theanuradha** [comment]
![image](https://user-images.githubusercontent.com/535713/226640783-2bd1f8d2-2a75-4904-b760-f3906ac2cd19.png)

**Comment by theanuradha** [comment]
@ifurnadjiev how can I remove this globally  or provide custom rwt-index.html

**Comment by ifurnadjiev** [comment]
Use HEAD HTML with custom CSS to override default settings globally:
https://github.com/eclipse-rap/org.eclipse.rap/blob/main/examples/org.eclipse.rap.examples/src/org/eclipse/rap/examples/internal/ExampleApplication.java#L35

**Comment by theanuradha** [comment]
@ifurnadjiev When use HEAD_HTML it go before 
![image](https://user-images.githubusercontent.com/535713/226975555-f7ef750f-f3cd-485a-8cdc-f66306325e7d.png)

**Comment by theanuradha** [comment]
this is what I set to HEAD_HTML
```" <style type=\"text/css\">\n"
                + "      div::-webkit-scrollbar {\n"
                + "        width: unset;\n"
                + "        height: unset;\n"
                + "      }\n"
                + "      div {\n"
                + "        scrollbar-width: unset;\n"
                + "      }\n"
                + "    </style>"````

**Comment by ifurnadjiev** [comment]
You can also use org.eclipse.rap.rwt.client.service.ClientFileLoader.requireCss(String) to load CSS at runtime.

**Comment by theanuradha** [comment]
@ifurnadjiev ClientFileLoader.requireCss helps with load order  but it not override and bring native scroll EG:
![image](https://user-images.githubusercontent.com/535713/227112691-4f3ee8ca-f28a-4ea9-a824-34ce3cdc1c0d.png)


if I use browser tools to remove original properties then only it show native 
![image](https://user-images.githubusercontent.com/535713/227112799-cff49bf7-9982-4bde-b53c-33c60e2ef2de.png)

**Comment by ifurnadjiev** [comment]
The problem came from the values that you set. You keep width/height to 0.
