### ISSUE TITLE
Wrong version of commons-fileupload dependency in pom.xml of org.eclipse.rap.fileupload

### ISSUE THREAD

**Issue by bwolff** [eclipse-rap/org.eclipse.rap#63]
This seems to be a regression of #41 and #45. This issue affects the artefact and pom.xml file deployed to Maven Central. It possibly affects other Maven build setups as well, in which the pom.xml information is used to pull in the dependencies.

( I'm repeating my comment from here: https://github.com/eclipse-rap/org.eclipse.rap/issues/41#issuecomment-1259425071 )

I run into a Maven dependency resolution issue related to the version bump of `commons-fileupload` to 1.4.0 in my project. The resulting POM dependency entry of `org.apache.commons.fileupload` looks like this:

```
<dependency>
  <groupId>commons-fileupload</groupId>
  <artifactId>commons-fileupload</artifactId>
  <version>1.4.0</version>
</dependency>
```

It refers to version 1.4.0, but the actual version of the `commons-fileupload` artefact is 1.4. See: https://search.maven.org/artifact/commons-fileupload/commons-fileupload/1.4/jar

Maven treats versions 1.4 and 1.4.0 differently and fails to resolve the correct dependency from Maven central. The workaround is to enforce the version of the transitive `commons-fileupload` dependency to 1.4 (e.g. by using a [strict dependency constraint](https://docs.gradle.org/current/userguide/dependency_constraints.html)).

I'm not sure how the `pom.xml` is generated, but it probably takes the information from the bundle dependencies, which afaik requires the use of the 3 part semvers. So there might be a version incompatibility between the bundle and Maven dependency worlds.

NB: I should mention that I'm experiencing this problem in a Gradle build and haven't tested it with a Maven build. However, since the version in the pom does not correspond to the artefact version in Maven central, other Maven builds might run into this issue as well.

**Comment by bwolff** [comment]
Thanks a lot for taking care of this, @mknauer .

I tested the version in the tmp Maven repo and can confirm that this fixes the issue, no need for the workaround of pinning the `commons-fileupload` version anymore.

Checking the `MANIFEST.MF` of `commons-fileupload` shows that the `Bundle-Version` is `1.4.0`, but is otherwise specified as `1.4` in the Maven world. So resolving this dependency from a target platform probably works without problems, but not when resolving it via Maven. This mismatch is unfortunate and probably a legacy versioning issue on the `commons-fileupload` dep, but we can't change that.

I would recommend to fix it in the RAP pom.xml for 3.23 and call it a "known-issue" for 3.22 to be done with it ;).

Let me know if I can provide any further help.

Cheers,
Ben

**Comment by mknauer** [comment]
Thank you very much for your fast response and confirmation.
I clicked the "release" button of the staging repo, the updated content should appear in Maven Central soon.

Closing this bug as fixed.
