### ISSUE TITLE
How to run a RAP application in multiple browser tabs/windows, getting server session timeout message

### ISSUE THREAD

**Issue by biparida95** [eclipse-rap/org.eclipse.rap#68]
Hi Team,
I have two dispatcher and 2 UI server which are connected independently one to other one with UI and dispatcher, when i m clicking first UI server URl getting logon in browser and then try to click 2nd UI server URl then the first one is getting session timeout, i try to config as per stack over flow  In the META-INF folder of your web application, place a context.xml file with the following content:
<Context cookies="false">
</Context>

still getting same error, please suggest me how to approach on this issue to resolve.

Thanks and Regards,
Bikash.

**Comment by ifurnadjiev** [comment]
For such a questions please use RAP newsgroup [here](https://www.eclipse.org/forums/index.php?t=thread&frm_id=34). This will make your question more visible to the RAP community.
