### ISSUE TITLE
[RAP] [Grid] Enable focus on invisible column

### ISSUE THREAD

**Issue by ailiskovic** [eclipse-rap/org.eclipse.rap#69]
Right now, one can't set focus on columns that have false value for the visible variable on the grid. 

        Display display = new Display ();
        Shell shell = new Shell(display);
        shell.setLayout(new FillLayout());

        Grid grid = new Grid(shell, SWT.BORDER | SWT.V_SCROLL | SWT.H_SCROLL);
        grid.setCellSelectionEnabled(true);
        grid.setHeaderVisible(true);
        GridColumn column = new GridColumn(grid, SWT.NONE);
        column.setText("Column 1");
        column.setWidth(100);
        GridColumn column2 = new GridColumn(grid, SWT.NONE);
        column2.setText("Column 2");
        column2.setWidth(100);
        GridColumn column3 = new GridColumn(grid, SWT.NONE);
        column3.setText("Column 3");
        column3.setWidth(100);
        column3.setVisible(false);

        GridItem item1 = new GridItem(grid, SWT.NONE);
        item1.setText("Item");
        GridItem item2 = new GridItem(grid, SWT.NONE);
        item2.setText("Item2");

        shell.setSize(500, 500);
        shell.open();
        while (!shell.isDisposed()) {
            if (!display.readAndDispatch()) {
                display.sleep();
            }
        }
        display.dispose();

Column 3 called setVisible(false) and SWT error throws an exception when the focus is on the column 3.

I have a possibility to hide columns and if I set focus on one of them, server error message is displayed, and one need to restart the application. I would expect not to terminate the application if one focus on the column, which is not visible. 

[stacktrace.txt](https://github.com/eclipse-rap/org.eclipse.rap/files/9809941/stacktrace.txt)

**Comment by bwolff** [comment]
Hi @ailiskovic,

it seems like the exception is coming from the Nebula Grid widget sources. Afaik, the RAP enabled version of the Nebula widget is merely a port from SWT to RWT. My guess would be that the same exception would occur when using the original SWT version of the Nebula Grid. It would therefore be an issue to be filed with the Nebula widget itself. The RAP ported version should not change the original behaviour, even if it may be considered as a bug.

Best regards,
Ben

**Comment by ifurnadjiev** [comment]
Without investigating in details I tend to agree with @bwolff that if there is an issue, it comes from Nebula Grid original source code.

**Comment by ifurnadjiev** [comment]
@ailiskovic please check your code against SWT (Nebula Grid) and let as know if the issue persists there too.

**Comment by mheiss** [comment]
The issue is just reproducible in RAP. In SWT everything is working as expected. No exception is raised.

**Comment by ifurnadjiev** [comment]
From the stack trace it seems that you are somehow navigate to a cell, which is not visible. Please list the exact steps to reproduce the issue.

**Comment by ifurnadjiev** [comment]
BTW which RAP version are you using? I've tried to provoke the exception from the stack trace with your snippet without success with current RAP from `main` branch (RAP 3.23 M1).

**Comment by mheiss** [comment]
Sorry i realized that our snippet is incomplete. Will clarify that with @ailiskovic and update the issue accordingly.
We are currently using RAP 3.21.0

**Comment by ailiskovic** [comment]
Sorry for misunderstanding. This is the code sample: 

        Display display = new Display();
        Shell shell = new Shell(display);
        shell.setLayout(new FillLayout());

        Grid grid = new Grid(shell, SWT.BORDER | SWT.V_SCROLL | SWT.H_SCROLL);
        grid.setCellSelectionEnabled(true);
        grid.setHeaderVisible(true);

        grid.addListener(SWT.KeyDown, e -> {
            System.out.println(e.character);
        });

        GridColumn column = new GridColumn(grid, SWT.NONE);
        column.setText("Column 1");
        column.setWidth(100);
        GridColumn column2 = new GridColumn(grid, SWT.NONE);
        column2.setText("Column 2");
        column2.setWidth(100);
        GridColumn column3 = new GridColumn(grid, SWT.NONE);
        column3.setText("Column 3");
        column3.setWidth(100);
        column3.setVisible(false);

        GridItem item1 = new GridItem(grid, SWT.NONE);
        item1.setText(2, "Item");
        GridItem item2 = new GridItem(grid, SWT.NONE);
        item2.setText(1, "Item2");
        GridItem item3 = new GridItem(grid, SWT.NONE);
        item3.setText(2, "Item3");

        shell.setSize(500, 500);
        shell.open();

        while (!shell.isDisposed()) {
            if (!display.readAndDispatch()) {
                display.sleep();
            }
        }
        display.dispose();`

The problem is, if I navigate to the cell, which is not visible, the error occurs. This happens if one uses a listener for pressing a key on the keyboard (in the example a simple print of a key). 

Steps to reproduce the error: 
- navigate to the second column and set focus on one of the cells 
- press right arrow on the keyboard

In SWT everything works as expected, one only gets an error with RAP. 

In addition I have uploaded a new stacktrace 

[stacktrace2.txt](https://github.com/eclipse-rap/org.eclipse.rap/files/9852114/stacktrace2.txt)
