### ISSUE TITLE
TypeError when POST fails causes error-dialog is not shown

### ISSUE THREAD

**Issue by ceisserer** [eclipse-rap/org.eclipse.rap#88]
Since RAP switched to using fetch instead of XHR, the ~"connection problem" dialog does no longer appear.
Instead the application just grays out like it does when waiting for a response from the server.

The reason is a type error:
![type_error](https://user-images.githubusercontent.com/14094579/203998559-3dfe039d-a41a-46af-a757-7ce0a601225b.jpg)

rap-client.js:31494          Uncaught (in promise) TypeError: Failed to fetch
    at rwt.remote.Request._sendWithFetch (rap-client.js:31494:5)
    at rwt.remote.Request.send (rap-client.js:31446:12)
    at Object.sendImmediate (rap-client.js:63503:17)
    at Object.<anonymous> (rap-client.js:63416:12)
    at Object._dispatchEvent (rap-client.js:3855:18)
    at Object.dispatchEvent (rap-client.js:3796:12)
    at Object._oninterval (rap-client.js:4469:16)
    at rap-client.js:624:17
_sendWithFetch @ rap-client.js:31494
send @ rap-client.js:31446
sendImmediate @ rap-client.js:63503
(anonymous) @ rap-client.js:63416
_dispatchEvent @ rap-client.js:3855
dispatchEvent @ rap-client.js:3796
_oninterval @ rap-client.js:4469
(anonymous) @ rap-client.js:624
Promise.then (async)
_sendWithFetch @ rap-client.js:31502
send @ rap-client.js:31446
sendImmediate @ rap-client.js:63503
(anonymous) @ rap-client.js:63416
_dispatchEvent @ rap-client.js:3855
dispatchEvent @ rap-client.js:3796
_oninterval @ rap-client.js:4469
(anonymous) @ rap-client.js:624
setInterval (async)
_applyEnabled @ rap-client.js:4381
func @ rap-client.js:2929
start @ rap-client.js:4400
send @ rap-client.js:63476
(anonymous) @ rap-client.js:63421
_dispatchEvent @ rap-client.js:3855
dispatchEvent @ rap-client.js:3796
_oninterval @ rap-client.js:4469
(anonymous) @ rap-client.js:624
setInterval (async)
_applyEnabled @ rap-client.js:4381
func @ rap-client.js:2929
start @ rap-client.js:4400
sendDelayed @ rap-client.js:63469
notify @ rap-client.js:64741
_sendBounds @ rap-client.js:51483
_onWindowResize @ rap-client.js:51454
_dispatchEvent @ rap-client.js:3855
dispatchEvent @ rap-client.js:3796
createDispatchEvent @ rap-client.js:3744
_onwindowresize @ rap-client.js:15662
(anonymous) @ rap-client.js:624
rwt-resources/themes/images/4f61765f.gif:1          GET http://127.0.0.1:8080/rwt-resources/themes/images/4f61765f.gif net::ERR_CONNECTION_REFUSED

**Comment by ifurnadjiev** [comment]
Any pointer how to reproduce it?

**Comment by ceisserer** [comment]
I triggered it by starting an empty EntryPoint example project from within eclispe. 
Once the browser had loaded the RAP application, I simply stopped the server and resized the browser window - which went grey but didn't show the dialog.

**Comment by ifurnadjiev** [comment]
ok... I can reproduce it
