### ISSUE TITLE
No jface.databinding.swt.typed package?

### ISSUE THREAD

**Issue by LorenzoBettini** [eclipse-rap/org.eclipse.rap#91]
The old deprecated databinding classes, e.g., org.eclipse.jface.databinding.swt.WidgetProperties, have been removed in 2022-12 (they have been replaced by org.eclipse.jface.databinding.swt.typed.WidgetProperties).
Is RAP planning to provide a org.eclipse.jface.databinding.swt.typed package.

Otherwise, we would not be able to do single sourcing with databinding.

thanks in advance
Lorenzo

**Comment by ifurnadjiev** [comment]
Can you give the PR a try? Is this everything you need? I've updated only the classes needed for org.eclipse.jface.databinding.swt.typed.WidgetProperties to compile.

**Comment by LorenzoBettini** [comment]
@ifurnadjiev thank you for the quick answer!
Actually, I'm also using the new `org.eclipse.jface.databinding.viewers.typed.ViewerProperties`, which replaces the removed `org.eclipse.jface.databinding.viewers.ViewersObservables`

This is the commit where I switched to the new classes: https://github.com/eclipse-emf-parsley/emf-parsley/commit/0f753a873f7d8c4fcdf2a997726f1c7f3173d053

**Comment by ifurnadjiev** [comment]
The "viewers" packages have been updated too.

**Comment by LorenzoBettini** [comment]
Great!
Is there a p2 repo I can use to test it? (I can't do that today anyway)

**Comment by ifurnadjiev** [comment]
https://ci.eclipse.org/rap/job/rap-head-runtime-github/76/

**Comment by LorenzoBettini** [comment]
Just zip files, right? No P2 repo?

**Comment by ifurnadjiev** [comment]
The zip file is a p2 repo.

**Comment by LorenzoBettini** [comment]
@ifurnadjiev I tried that and it compiles now, but I can't run applications because the new packages are not exported in the RAP databinding MANIFEST.MF.

On a side note, I think that archiving a p2 repository (with its filesystem layout) is better than archiving a zip file: with a p2 repository directory, it can be easily consumed even in the CI. Or is it possible to use directly a zip file in a TP?

thanks again

**Comment by ifurnadjiev** [comment]
Exported new packages in the MANIFEST.MF.

**Comment by ifurnadjiev** [comment]
> On a side note, I think that archiving a p2 repository (with its filesystem layout) is better than archiving a zip file: with a p2 repository directory, it can be easily consumed even in the CI. Or is it possible to use directly a zip file in a TP?

In the target platform select "Software site" and choose the zip file from your local file system.

**Comment by LorenzoBettini** [comment]
I was talking about CI (e.g., on Jenkins or GitHub Actions), to easily consume nightly p2 sites.

**Comment by mknauer** [comment]
The job https://ci.eclipse.org/rap/view/RAP%20main%20branch/job/rap-head-runtime-signed/ creates all nightly and all release builds that we are publishing. A part of this job is the p2 repositories that can be consumed directly.

Just start with the URL https://ci.eclipse.org/rap/view/RAP%20main%20branch/job/rap-head-runtime-signed/lastSuccessfulBuild/artifact/org.eclipse.rap/releng/org.eclipse.rap.build/ and follow the directory links depending on what you like to consume, i.e. Eclipse 3 or Eclipse 4 builds.

**Comment by LorenzoBettini** [comment]
Thanks @mknauer 
I was talking about the other job https://ci.eclipse.org/rap/job/rap-head-runtime-github/ where @ifurnadjiev fixed the databinding problem.

**Comment by LorenzoBettini** [comment]
@ifurnadjiev, by the way, everything's now fixed from our (EMF Parsley) side! Thanks a lot for fixing this :)
This will be part of 2022-12, won't it?
Do you have an estimate on when it will be integrated in simrel?

**Comment by ifurnadjiev** [comment]
I hope that it will be part of RC2 this week. cc: @mknauer

**Comment by LorenzoBettini** [comment]
@ifurnadjiev @mknauer For me the PR https://github.com/eclipse-rap/org.eclipse.rap/pull/92 fixes the problems. I see it's not merged yet, so I guess it's not yet available from the nightly update site (https://ci.eclipse.org/rap/view/RAP%20main%20branch/job/rap-head-runtime-signed/lastSuccessfulBuild/artifact/org.eclipse.rap/releng/org.eclipse.rap.build/repository/target/repository/), is it?

**Comment by ifurnadjiev** [comment]
Not yet

**Comment by mknauer** [comment]
> ...This will be part of 2022-12, won't it? Do you have an estimate on when it will be integrated in simrel?

We just finished reviewing the pull request. Should be included in our RC2 contribution tomorrow (Wednesday) if things go well. Unfortunately not earlier...

> ...I see it's not merged yet, so I guess it's not yet available from the nightly update site...

Correct, the pull request is not yet merged, and not yet included in the nightly build p2 repository.
But I changed the configuration of our GitHub verification job [rap-head-runtime-github](https://ci.eclipse.org/rap/view/RAP%20main%20branch/job/rap-head-runtime-github/) to archive the p2 repositories like our other jobs, and serve it somewhere below [rap-head-runtime-github/lastSuccessfulBuild/artifact/org.eclipse.rap/releng/org.eclipse.rap.build/](https://ci.eclipse.org/rap/view/RAP%20main%20branch/job/rap-head-runtime-github/lastSuccessfulBuild/artifact/org.eclipse.rap/releng/org.eclipse.rap.build/) - just drill down to the `repositoriy` directory.

**Comment by mknauer** [comment]
> > ...This will be part of 2022-12, won't it? Do you have an estimate on when it will be integrated in simrel?
> 
> We just finished reviewing the pull request. Should be included in our RC2 contribution tomorrow (Wednesday) if things go well. Unfortunately not earlier...

It was merged yesterday, and is now available in our regular RC2 contribution to SimRel.

**Comment by LorenzoBettini** [comment]
Thanks, but I still don't see RC2 here https://download.eclipse.org/releases/2022-12/

**Comment by LorenzoBettini** [comment]
OK, I think you meant this one https://download.eclipse.org/staging/2022-12 right?

**Comment by mknauer** [comment]
> OK, I think you meant this one https://download.eclipse.org/staging/2022-12 right?

Exactly. RC2 is not yet published and/or will be published next week as final release.
