### ISSUE TITLE
Mouse up / down event not triggering on table header click or select

### ISSUE THREAD

**Issue by Devip-singh** [eclipse-rap/org.eclipse.rap#93]
Hello,

We have upgraded our RAP version in our WAR file from 2.1 to 3.10 and deployed it on Jboss7. We have observed that:

1. mouse events are not working on table header
2. Combo box multiple character search stopped working . i.e. Instead of entering one character that takes you to the first instance of a word... if you enter two characters... you get the closer match

These features were working fine with RAP 2.1

From RAP community, I get to know that mouse events are NOT triggered in Table/Tree header. This change has been introduced here:
https://git.eclipse.org/r/c/rap/org.eclipse.rap/+/22050/

Could you please let us know when you are planning to fix this issue. This is a bit urgent as customer go live is blocked.

Here is the code snippets that we have used. It is a high level information and I am hopeful that it will help you to understand the situation.

We have class `HeaderSortListener` that implements `MouseListener`

```java
public class HeaderSortListener implements MouseListener {
    /**
     * {@inheritdoc}
     */
    public void mouseDoubleClick(MouseEvent pE)
    {
        // TODO Auto-generated method stub
    }

    /**
     * {@inheritdoc}
     */
    public void mouseDown(MouseEvent pE)
    {
        // TODO Auto-generated method stub
    }

    /**
     * {@inheritdoc}
     */
    public void mouseUp(MouseEvent pE)
    {
// This function has business logic that perform the sort. Ideally this function should get called when table header is clicked.
// Observation : This function was getting called when we were using RAP 2.1. Once we upgraded RAP version to RAP 3.10 , This function is no more called on table header click.
    }
}
```

We have a `initialize()` method in a class from where we are registering header sort listener.

```java
public class CustomMassTable  extends Composite
    implements TraverseListener, DragDetectListener, ModifyListener, IDoubleClickListener, DropTargetListener,
    IFilterListener, IErrorListener, KeyListener, IModifiable, IValidable
{
// Few instance variable and other stuff
private MouseListener headerSortListener;
private Table table;
private CheckboxTableViewer tableViewer;
public CustomMassTable(Composite pParent, int pStyle, boolean pMultiSelection, boolean pCheckLine, boolean headerVisible,
        Class<?> pObjectClass)
    {
        super(pParent, pStyle | SWT.NO_FOCUS);
        // Some initiation 
        initialize(descriptor);

    }

private void initialize(CustomMassTableDescriptor pDescriptor)
    {
// Some processing and layout build
table = new Table(middleComposite, tableStyleFlag);
tableViewer = new CheckboxTableViewer(table);
headerSortListener = new HeaderSortListener(this, sortIndex);
table.addMouseListener(columnSortListener); // This is responsible for registering the mouse event on table header and 
                                                                          //should call mouseup(MouseEvent pE)
}

}
```

**Comment by ifurnadjiev** [comment]
If you want to react on sort indicator click use a selection listener on the column like in the example below:
```
      column.addSelectionListener( new SelectionAdapter() {
        @Override
        public void widgetSelected( SelectionEvent event ) {
          Table table = column.getParent();
          if( table.getSortColumn() == column ) {
            if( table.getSortDirection() == SWT.UP ) {
              table.setSortDirection( SWT.DOWN );
            } else {
              table.setSortDirection( SWT.UP );
            }
          } else {
            table.setSortDirection( SWT.UP );
            table.setSortColumn( column );
          }
        }
      } );
```

**Comment by ifurnadjiev** [comment]
As I already stated in the newsgroup, in SWT the mouse listener is not triggered on Table column header. RWT tries to keep the exact same behavior like in SWT.

**Comment by Devip-singh** [comment]
@ifurnadjiev 
Thanks for reply but please do not mark this invalid. These things were working fine 2.1 version RAP , so so ideally they should work with 3.10. Please let me know why it is not working anymore.

We can not go with above logic as that will bring huge changes as sorting logic is quite different and depend on few more parameter. I can not share those details because of confidentiality issue.

**Comment by ifurnadjiev** [comment]
Your code is not working on SWT and it will not work on RAP as well. The old 2.x behavior can be considered as a bug, which was fixed in 3.x. We can consider fixing only something that works in SWT but not in RAP.

**Comment by ifurnadjiev** [comment]
... and here are the official SWT snippets how to deal with sorting:

https://github.com/eclipse-platform/eclipse.platform.swt/blob/master/examples/org.eclipse.swt.snippets/src/org/eclipse/swt/snippets/Snippet2.java

https://github.com/eclipse-platform/eclipse.platform.swt/blob/master/examples/org.eclipse.swt.snippets/src/org/eclipse/swt/snippets/Snippet192.java

All SWT snippets can be found [here](https://www.eclipse.org/swt/snippets/).

**Comment by Devip-singh** [comment]
@ifurnadjiev 
What do you suggest for this  :
Combo box multiple character search stopped working . i.e. Instead of entering one character that takes you to the first instance of a word... if you enter two characters... you get the closer match

**Comment by ifurnadjiev** [comment]
Let keep this issue about Table header only. 
Please open a separate issue with a snippet to reproduce it. Does it work in SWT as you expect?
