### ISSUE TITLE
Wrong handling error in ServerPush.js / Connections.js

### ISSUE THREAD

**Issue by nzanaga** [eclipse-rap/org.eclipse.rap#98]
With the fix  https://github.com/eclipse-rap/org.eclipse.rap/pull/90  
error is catched, but not correctly handled by ServerPush.js / Connections.js  

when a ServerPush issue a request, and there is an error, inside '_handleError'  check 
rwt.remote.Connection.getInstance()._isConnectionError( event.status )  

but now "event.status" is undefined and _isConnectionError  return false.
I have modified _isConnectionError adding also condition   || statusCode === undefined  
and works fine.

To test simply activate a serverpush request, next disable/enable network cable, then do any action, without "statusCode === undefined" there is no any retry in serverpush request

**Comment by ifurnadjiev** [comment]
Please create a PR with this change. The way you fix it is the correct way.
